language: ruby
rvm:
  - 2.2.2
sudo: required
branches:
  only:
  - master
addons:
  apt:
    packages:
    - netpbm
    - texlive
    - texlive-latex-extra
install:
- travis_retry sudo apt-get install -y xzdec
- travis_retry bundle install
- travis_retry npm install phantomjs -g
- travis_retry npm install casperjs -g
- sudo -i /usr/bin/tlmgr init-usertree
env:
  global:
  - secure: d3OvGe1OUFcfcBVQq7uEUMAhTQQN2/e5Ex27hS631kSXJ/nR5+Vo1Ub+PctEgmJ7FC1kksDTYcNZLTaunNKCPc3iqVvuFPF2KXBoFESswb7WnrIdSyL+fpgsdcetMEgbzHo97l8JV65k02GDtXd5mZ3m/WoE2KZl8RwNGJxwvXY=
before_install:
- set -e
- openssl aes-256-cbc -K $encrypted_b5b51a553100_key -iv $encrypted_b5b51a553100_iv
  -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh
- chmod 600 ~/.ssh/id_rsa
script:
- set -e
- latex --version
- dvips --version
- pnmalias --version
- pnmcrop --version
- pnmtopng --version
- _test/run.sh
- git config --global user.email "travis@teamed.io"
- git config --global user.name "travis"
- jgd -u git@github.com:teamed/technoparkcorp.com.git
