language: ruby
branches:
  only:
    - master
install:
  - sudo apt-get install -y netpbm texlive texlive-latex-extra
  - bundle install
  - npm install phantomjs -g
  - npm install casperjs -g
env:
  global:
    - secure: "d3OvGe1OUFcfcBVQq7uEUMAhTQQN2/e5Ex27hS631kSXJ/nR5+Vo1Ub+PctEgmJ7FC1kksDTYcNZLTaunNKCPc3iqVvuFPF2KXBoFESswb7WnrIdSyL+fpgsdcetMEgbzHo97l8JV65k02GDtXd5mZ3m/WoE2KZl8RwNGJxwvXY="
script:
  - set -x
  - set -e
  - _test/run.sh
  - git config --global user.email "travis@teamed.io"
  - git config --global user.name "travis"
  - jgd -u https://yegor256:$PASSWORD@github.com/teamed/technoparkcorp.com.git

